# Deployment file for docker-compose with Coolify.
# We only have non-db services in this file as database services are created and managed with Coolify directly.
version: "3.8"

services:
    api:
        build:
            context: services/api
            dockerfile: docker/Dockerfile
        ports:
            - "3000:3000"

    prefect-server:
        build:
            context: services/pipelines
            dockerfile: docker/Dockerfile.deploy
            target: server
        restart: always
        volumes:
            - prefect:/root/.prefect
        entrypoint: [ "prefect", "server", "start" ]
        env_file:
            - .env
        environment:
            - PREFECT_SERVER_API_HOST=0.0.0.0
            - PREFECT_API_URL=http://host:4200/api
            - PREFECT_API_DATABASE_CONNECTION_URL=${DATABASE_URL}
            - PREFECT_API_DATABASE_MIGRATE_ON_START=True
        ports:
            - 4200:4200

    prefect-flows:
        build:
            context: services/pipelines
            dockerfile: docker/Dockerfile.deploy
            target: flows
        entrypoint: [ "python", "/app/code/main.py" ]
        env_file:
            - .env
        restart: always
        depends_on:
            - prefect-server
        environment:
            - PREFECT_API_URL=http://prefect-server:4200/api
            - PYTHONPATH=/app/code

volumes:
    prefect:
