version: "3.8"

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 5499:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/ # Make db data persist

volumes:
  pg-data:
